dist: trusty
sudo: required
services:
- docker

# only build master branch (and PRs)
branches:
  only:
    - "master"

language: go
go:
- "1.14"

env:
  - GO111MODULE=on
    GOFLAGS=-mod=vendor

install:
- make init

script:
- make test
- make build
- make terraform-fmt
- make terraform-lint
- make website-test
